### PR TITLE
Annotations

### PR DESCRIPTION
**Pull request by zkayyali812**
Signed-off-by: Zachary Kayyali <zkayyali@redhat.com>
https://github.com/open-cluster-management/backlog/issues/16663

### CODE REVIEW

**Comment by JakobGray** [comment]
Added suggested changes [here](https://github.com/zkayyali812/backplane-operator/pull/5)

**Comment by zkayyali812** [comment]
Thanks for the update Jake!

**Review by JakobGray — APPROVED** [review]

**Pull request merged**
