### PR TITLE
Install Clustermanager and Hive Operator bundles

### PR DESCRIPTION
**Pull request by zkayyali812**
Signed-off-by: Zachary Kayyali <zkayyali@redhat.com>

### CODE REVIEW

**Review by JakobGray — APPROVED** [review]
lgtm. Up to you if you want to merge these changes in now or debug the clustermanager issue further first

**Comment by zkayyali812** [comment]
@JakobGray 
Please rereview - I fixed the clustermanager bug shown this morning.

When a clustermanager is created, it creates and deploys resources in the `open-cluster-management-hub` namespace.
When the clustermanager CR is deleted, it triggers the deletion of the ocm-hub namespace, but the CR has no finalizer and does not wait for the namespace to be removed.

The fix implemented was to first delete the clustermanager CR, wait explicitly for the ocm-hub namespace to be removed, then proceed with the rest of the uninstallation.

**Comment by zkayyali812** [comment]
/hold

We should sync this PR along with release-repo

**Review by JakobGray — APPROVED** [review]

**Pull request merged**
