### PR TITLE
Add clustermanagementaddon resource

### PR DESCRIPTION
**Pull request by qiujian16**
Signed-off-by: Jian Qiu <jqiu@redhat.com>

### CODE REVIEW

**Comment by JakobGray** [comment]
@qiujian16 can you link an issue to this PR?

**Comment by zkayyali812** [comment]
The unit-test is failing since the CRD `ClusterManagementAddOn` is not available at runtime.

This CRD is rather installed when the `cluster-manager` CR is installed.

In order to get this to pass the test, we would either need to refactor how the `ClusterManagementAddon` is installed, or add the ClusterManagementAddon CRD to our list of CRDs which is installed at runtime.

**Comment by zkayyali812** [comment]
@qiujian16 After discussing w/ squad, since the CRD is not in place before applying the ClusterManagementAddon resource, and since the ClusterManager CR installs the ClusterManagementAddon CRD, would it be possible to close out this PR and have ClusterManager install the ClusterManagementAddon work-manager resource?

**Comment by qiujian16** [comment]
ClusterManager is to install the crd  of ClusterManagementAddOn but not a certain CR. Is it possible that we can apply this  resource after ClusterManager is installed?

**Pull request closed without merging**
