### PR TITLE
add clusterpool/claim permission in cluster admin

### PR DESCRIPTION
**Pull request by ldpliu**
foundation need to inject clusterpool related resource admin and view permission to clusterrole "admin".

### CODE REVIEW

**Review by JakobGray — CHANGES_REQUESTED** [review]
If the permissions are for the foundation components they should go in the `pkg/templates/charts/server-foundation/templates` directory where the backplane operator will apply them. The `config` directory is meant for resources relating to the backplane-operator itself.

**Comment by ldpliu** [comment]
@JakobGray @zkayyali812 I have move these roles to foundation template, please  review it.

**Pull request merged**
